version: '3.8'

services:
  sentiment_analysis:
    image: datascientest/fastapi:1.0.0
    container_name: sentiment_analysis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/status')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  first_test:
    build:
      context: .
      dockerfile: DockerFile.first_test
    image: first_test:latest
    container_name: first_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
    restart: "no"
    # Don't start automatically - will be controlled by orchestrator
    #profiles: ["manual"]

  second_test:
    build:
      context: .
      dockerfile: DockerFile.second_test
    image: second_test:latest
    container_name: second_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
      restart: "no"
    
  third_test:
    build:
      context: .
      dockerfile: DockerFile.third_test
    image: third_test:latest
    container_name: third_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
      second_test:
        condition: service_completed_successfully
    restart: "no"