version: '3.8'

services:
  sentiment_analysis:
    image: datascientest/fastapi:1.0.0
    container_name: sentiment_analysis
    ports:
      - "8000:8000"

  first_test:
    build:
      context: .
      dockerfile: DockerFile.first_test
    image: first_test 
    container_name: first_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1

  second_test:
    build:
      context: .
      dockerfile: DockerFile.second_test
    image: second_test
    container_name: second_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1
    
  third_test:
    build:
      context: .
      dockerfile: DockerFile.third_test
    image: third_test
    container_name: third_test_container
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG=1
