version: '3.8'

services:
  sentiment_analysis:
    image: datascientest/fastapi:1.0.0
    container_name: sentiment_analysis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  first_test:
    build:
      context: .
      dockerfile: DockerFile.first_test
    container_name: first_test_container
    volumes:
      - ./logs:/app/logs
      - ./status:/app/status
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
    restart: "no"
    # Don't start automatically - will be controlled by orchestrator
    profiles: ["manual"]

  second_test:
    build:
      context: .
      dockerfile: DockerFile.second_test
    container_name: second_test_container
    volumes:
      - ./logs:/app/logs
      - ./status:/app/status
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
    restart: "no"
    # Don't start automatically - will be controlled by orchestrator
    profiles: ["manual"]
    
  third_test:
    build:
      context: .
      dockerfile: DockerFile.third_test
    container_name: third_test_container
    volumes:
      - ./logs:/app/logs
      - ./status:/app/status
    environment:
      - LOG=1
      - API_HOST=http://sentiment_analysis
    depends_on:
      sentiment_analysis:
        condition: service_healthy
    restart: "no"
    # Don't start automatically - will be controlled by orchestrator
    profiles: ["manual"]